public with sharing class gitchangestes {
    public gitchangestes() {
         system.debug('lalallala');
    }
     public gitchangestes222() {
         system.debug('lalallala');
    }
     public gitchangestes33() {
         system.debug('lalallala');
     }
     public gitchnages44()
     {
        system.debug('gitchanges');
     }
     public gitchnages55()
     {
        system.debug('gitchanges');
     }
     public gitchnagesdev()
     {
        system.debug('gitdevchchanges');
     }

}